theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  pages:
    index:
      truncate_description: 0
  summary:
    position: hero
  search:
    active: true
  debug:
    productionUrl: "https://www.iut.u-bordeaux-montaigne.fr"