posts:          /actualites/:year/:month/:day/:slug/
categories:     /actualites/:slug/
persons:        /notre-institut/ressources/equipe/:slug/
authors:        /notre-institut/ressources/equipe/:slug/actualites/
diplomas:       /formation/offre-de-formation/diplomes/:slug/
administrators: /notre-institut/ressources/equipe/:slug/roles/
teachers:       /notre-institut/ressources/equipe/:slug/programs/
researchers:    /notre-institut/ressources/equipe/:slug/papers/
