name: Percy

on:
  pull_request:
    branches:
      - main

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ secrets.HUGO_VERSION }}
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Percy Test
        uses: BerniWittmann/background-server-action@latest
        with: 
          command: npx @percy/cli snapshot snapshots.yml
          start: hugo server -e ${{ secrets.HUGO_ENV }} --minify
          wait-on: 'http://localhost:1313'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
