name: Percy

on:
  # Used to trigger a base analysis
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ secrets.HUGO_VERSION }}
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Start Hugo server
        # https://discourse.gohugo.io/t/run-server-as-background/3252/2
        run: hugo server -e ${{ secrets.HUGO_ENV }} --minify &

      - name: Percy Test
        run: npx @percy/cli snapshot snapshots.yml
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
